<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Password_btnShowPassword</name>
   <tag></tag>
   <elementGuidId>a288e7ba-5b7d-40db-8179-50b1c30d283b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btnShowPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnShowPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2131149-20ec-48b2-b3bf-d0a4aedb72cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/projectx/images/login/eye.svg</value>
      <webElementGuid>5387d211-6dc2-4242-b9c1-e057147514ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>17724772-bd5b-4e22-99e4-aefabcf0ae75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShowPassword</value>
      <webElementGuid>433da38b-e993-4e77-b6dc-19c702ac3eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShowPassword&quot;)</value>
      <webElementGuid>f9e1dc9d-b535-403e-af83-066d2c084af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91205ca3-a554-4cd4-889c-27a74d3f02e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/projectx/images/login/eye.svg</value>
      <webElementGuid>52d3c8d2-53ff-474c-ba4b-8e31d8be2206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>4bde0348-a6d9-441b-89c7-4daa26f75a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShowPassword</value>
      <webElementGuid>0c8bb1d4-6752-483a-b522-6a5c5b637c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShowPassword&quot;)</value>
      <webElementGuid>58a07d03-6f9d-4057-af2a-4a415155cd22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btnShowPassword']</value>
      <webElementGuid>8d0b4616-4f0a-4325-9d1c-58539a760825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[4]/div/div/button/img</value>
      <webElementGuid>5c344f31-26ca-45bc-8bde-e6812fffc6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='eye']</value>
      <webElementGuid>014bb46c-694c-4672-bfe0-9c052de9d003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>086c16b7-2e80-461f-868e-e6c292e0134b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/resources/projectx/images/login/eye.svg' and @alt = 'eye' and @id = 'btnShowPassword']</value>
      <webElementGuid>5064b757-2c61-46c8-bb0e-e08cd2cc06b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
