<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>informationOptionSelect</name>
   <tag></tag>
   <elementGuidId>d7e91565-ccbe-4ce7-95fd-8a8402dd34f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='registerReferralId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registerReferralId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92036a2c-fc52-4d91-85e8-eeac4103c252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>267998ca-bc0c-432b-8200-c28cde64deb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>0b18f8c4-c120-4d73-b38d-8ad1b400815f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>469313a1-3267-4464-9225-7b1ee3c5c257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>318ba12e-7813-45a8-ae4e-9d93fe3eba14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>3f42fbc1-82d6-4f80-b93b-0bcdb35ab4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bde3f983-7853-47cd-89cc-014d751346a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>40079817-1530-454b-827d-e0d9edbc1c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>694a4bfe-7f23-41e2-b134-0b447cbb60ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>82d84b3a-05c8-4b2f-bba0-218c73d50fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>53c7cf2c-697e-4125-9de0-25135f31017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>c669e482-670c-4f00-81c5-db259b9be55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b79922b4-2438-4c64-bfbe-0aef22d7e282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>bfccb952-5ea6-452a-ad28-692f7d7aab4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>08277284-2397-46fe-af85-cd81291bf163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cbc88a2c-5b90-4054-a740-9ff2f1538bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>567210b0-7298-4efd-9867-dddefa4eb6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>6adb9d53-c718-4418-8cef-de71ae4a23f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='registerReferralId']</value>
      <webElementGuid>35203be1-165a-4b51-b604-bf417f16a005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[7]/select</value>
      <webElementGuid>f2256ce7-7609-4063-9baa-61de2ce96b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana Kamu tahu ALAMI? (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>5a89123b-9fd5-4ab4-b5b9-7ac2c5a536ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>a4e60952-6007-485a-b8aa-76cf2e10103c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::select[1]</value>
      <webElementGuid>d23c4825-ac41-47d9-be09-249c3045c9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar disini'])[1]/preceding::select[1]</value>
      <webElementGuid>9d917e86-c748-421e-90c5-5e75ae7e726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>426dba2f-9841-4289-b47b-5fbe98efbe25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'registerReferralId' and @name = 'registerReferralId' and (text() = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ' or . = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ')]</value>
      <webElementGuid>e9ff18d8-9120-48b5-88a9-2e713f05929e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
