<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validasiCheckbok1</name>
   <tag></tag>
   <elementGuidId>09df447e-15c0-4f4c-90ae-4f8a7ac7a12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='langganan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;langganan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea490193-6381-4067-a93a-da7839af4701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>69a56c13-8253-4720-91a6-6715ab70455f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>langganan</value>
      <webElementGuid>7f9f0951-d9f3-4db9-ac57-703d06671e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;wrapper-footer&quot;]/label[@class=&quot;text-light-check&quot;]/input[1]</value>
      <webElementGuid>5636d138-ccdf-4787-91a9-b316723c9284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc99a59a-5646-440e-8042-1fd0a6117fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e647281e-c21b-41ec-997f-01c20276ed43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>langganan</value>
      <webElementGuid>c078798e-54ca-4b6b-9deb-4d735765a794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;wrapper-footer&quot;]/label[@class=&quot;text-light-check&quot;]/input[1]</value>
      <webElementGuid>f5d985cd-a442-41e1-8c57-313fb17756c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91562736-ef24-4b94-bdc1-af8782f41482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>17282def-d2ff-4c28-8e3b-722151062bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>langganan</value>
      <webElementGuid>574dfc3b-dfb2-48d6-8160-1ecb1eca946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;wrapper-footer&quot;]/label[@class=&quot;text-light-check&quot;]/input[1]</value>
      <webElementGuid>4fdab96b-9cfd-4316-b7ee-98be0198f297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='langganan']</value>
      <webElementGuid>0b8c07d7-ae97-40b0-978e-7a8a47720e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[2]/label/input</value>
      <webElementGuid>b8a9e5b0-dd96-4d46-beec-06cbc12df5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>39201462-a8dd-4d16-9b55-c836af558893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'langganan']</value>
      <webElementGuid>fe27f538-8db6-4b34-a7ee-f712ce9366f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
